"""empty message

Revision ID: 1f82ee762627
Revises: 
Create Date: 2018-04-26 00:06:18.559768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f82ee762627'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease',
    sa.Column('disease_id', sa.String(length=128), nullable=False),
    sa.Column('disease_name', sa.Text(), nullable=True),
    sa.Column('disease_synonyms', sa.Text(), nullable=True),
    sa.Column('disease_category', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('disease_id')
    )
    op.create_table('food',
    sa.Column('food_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('common_names', sa.Text(), nullable=True),
    sa.Column('scientific_name', sa.Text(), nullable=True),
    sa.Column('food_category', sa.String(length=128), nullable=True),
    sa.Column('tax_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('food_id')
    )
    op.create_table('gene',
    sa.Column('gene_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('gene_id')
    )
    op.create_table('references',
    sa.Column('pmid', sa.Integer(), nullable=False),
    sa.Column('authors', sa.String(length=512), nullable=True),
    sa.Column('date', sa.String(length=128), nullable=True),
    sa.Column('journal_name', sa.String(length=512), nullable=True),
    sa.Column('journal_name_abbr', sa.String(length=512), nullable=True),
    sa.Column('publication_type', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('pmid')
    )
    op.create_table('disease_gene',
    sa.Column('gene_id', sa.String(length=128), nullable=False),
    sa.Column('disease_id', sa.String(length=128), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.disease_id'], ),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.gene_id'], ),
    sa.PrimaryKeyConstraint('gene_id', 'disease_id')
    )
    op.create_table('food_disease',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pmid', sa.Integer(), nullable=True),
    sa.Column('food_id', sa.String(length=128), nullable=True),
    sa.Column('disease_id', sa.String(length=128), nullable=True),
    sa.Column('association', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.disease_id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['food.food_id'], ),
    sa.ForeignKeyConstraint(['pmid'], ['references.pmid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_gene',
    sa.Column('food_id', sa.String(length=128), nullable=False),
    sa.Column('gene_id', sa.String(length=128), nullable=False),
    sa.Column('disease_categories', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.food_id'], ),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.gene_id'], ),
    sa.PrimaryKeyConstraint('food_id', 'gene_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_gene')
    op.drop_table('food_disease')
    op.drop_table('disease_gene')
    op.drop_table('references')
    op.drop_table('gene')
    op.drop_table('food')
    op.drop_table('disease')
    # ### end Alembic commands ###
