"""empty message

Revision ID: a8ce8461ae60
Revises: 5c05f95e7cba
Create Date: 2018-06-12 00:41:10.829028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ce8461ae60'
down_revision = '5c05f95e7cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemical_gene',
    sa.Column('pubchem_id', sa.String(length=128), nullable=False),
    sa.Column('gene_id', sa.String(length=128), nullable=False),
    sa.Column('interaction_actions', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.gene_id'], ),
    sa.ForeignKeyConstraint(['pubchem_id'], ['chemical.pubchem_id'], ),
    sa.PrimaryKeyConstraint('pubchem_id', 'gene_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chemical_gene')
    # ### end Alembic commands ###
