"""empty message

Revision ID: e81cbfd923e0
Revises: 30fd042d27a8
Create Date: 2018-06-18 13:48:52.015882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81cbfd923e0'
down_revision = '30fd042d27a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gene', sa.Column('gene_name', sa.Text(), nullable=True))
    op.add_column('gene', sa.Column('gene_symbol', sa.String(length=128), nullable=True))
    op.add_column('gene', sa.Column('organism', sa.Text(), nullable=True))
    op.add_column('gene', sa.Column('other_symbols', sa.Text(), nullable=True))
    op.add_column('gene', sa.Column('synonyms', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gene', 'synonyms')
    op.drop_column('gene', 'other_symbols')
    op.drop_column('gene', 'organism')
    op.drop_column('gene', 'gene_symbol')
    op.drop_column('gene', 'gene_name')
    # ### end Alembic commands ###
